weights: /user/a0132471/Files/bit-bucket/pytorch/yolov5_pose/runs/train/shared_models/person_detector/yolov5s6_person_64p8_90p2/weights/last.pt
cfg: ./models/hub/yolov5s6_kpts.yaml
data: ./data/coco_kpts.yaml
hyp: data/hyp.scratch.yaml
epochs: 300
batch_size: 96
img_size:
- 640
- 640
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
kpt_label: true
world_size: 1
global_rank: -1
save_dir: runs/train/exp5
total_batch_size: 96
